### ISSUE TITLE
What's the minimum sdk version this sample can support?

### ISSUE THREAD

**Issue by AlexSyx** [googlesamples/androidtv-Leanback#131]
Could it run on android 4.2 (SDK version 17) ?

**Comment by benbaxter** [comment]
Android TV launched with 5.0 Lollipop and the leanback support library was built with 21 as a baseline because of that.

It may be able to run on a lower version but that does not mean this sample has been tested and supported for lower versions. Feel free to update the [minsdk](https://github.com/googlesamples/androidtv-Leanback/blob/1165ae96fa9da1660abdf9cf3dbd953aec01e2b0/app/build.gradle#L8) and play around with the sample.
