### ISSUE TITLE
Demo app not working in fire tv

### ISSUE THREAD

**Issue by aravinds03** [googlesamples/androidtv-Leanback#42]
Hi,
Demo app is not working in fire tv.
Also, In SearchFragment, the default android speech recognizer is not working in amazon fire os.
So, is there any way to disable speech/microphone icon in SearchFragment?

**Comment by ryanseys** [comment]
Hi @aravinds03 thanks for reporting this issue and your interest in this sample. The Leanback sample showcases a number of Android TV specific features that are unfortunately not supported by Amazon Fire TV at this time, such as Voice Search. This sample is designed to be run on Android platforms of API 21+ due to the use of new APIs like [MediaSession](https://developer.android.com/reference/android/media/session/MediaSession.html) meaning that until Fire TV supports API 21+ this sample will not work.

**Comment by IgorGanapolsky** [comment]
FYI: Fire TV now uses API 22 (Lollipop) features and the Android v17 Leanback Library.  Discussed here: https://developer.amazon.com/public/solutions/devices/fire-tv/docs/using-the-fire-tv-sdk-samples
