### ISSUE TITLE
Progress dialog or AsyncTask unsupported in emulator?

### ISSUE THREAD

**Issue by neobie** [googlesamples/androidtv-Leanback#46]
Hi, I can't update this app to Android Emulator as it is installed as system app. What should I do?

**Comment by ryanseys** [comment]
That's an interesting issue. Can you tell me what version of Android Studio / Android you're running with the emulator so I can diagnose? We include the same app in the emulator so it's likely that these IDs are colliding.

**Comment by neobie** [comment]
Hi Ryan,

Check this out: https://drive.google.com/open?id=0B-LCl4SF8TXKYWhkMEw3TTJWbTg
Running latest Android Studio, emulator 720p API 22.

Can I request for more sample codes, eg: when navigate on left pane (category), the right pane only show list of movies from 1 category?
For example you can see official Youtube app, there are Highlights, Watchlist, History, etc. 
When selecting "Highlights", only "Highlights" videos are shown. When move to "Watchlist", only "Watchlist" videos are shown, as oppose to the sample here.

**Comment by testuser34** [comment]
Hello i m installing this google sample in my android studio.
then it's build successfully.
but whenever i launch it to android tv emulator created with api level 22 720p.
it showing this error.


DEVICE SHELL COMMAND: pm install -r "/data/local/tmp/com.example.android.tvleanback"
Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE]

it's every time showing this error.

can u pls help me out with this problem.

thanks in advance.

**Comment by ryanseys** [comment]
Hi, the application will need to be changed to a different unique identifier in order to be installed on the device. This is because we package the leanback sample as a system apk into the emulator. I'll discuss with my team on an appropriate fix but for now, you can launch on the emulator by changing the unique id in the app. Here are the lines that, if you change, should allow the app to work in the emulator:

https://github.com/googlesamples/androidtv-Leanback/blob/b09a46461b032265c61cdc66ba74714ea806f392/app/build.gradle#L7

https://github.com/googlesamples/androidtv-Leanback/blob/b09a46461b032265c61cdc66ba74714ea806f392/app/src/main/AndroidManifest.xml#L19

**Comment by testuser34** [comment]
Hi Ryanseys,
I have customized the android tv app,
Like My first screen is signin and then in other screen some listing and data show.
Then all the things working fine while i am running app in emulator.
But when it is been installed in Android TV device the web service call is not working in While clicking in sign up button,
It is redirected to home screen always while click on sign in button.
Then as i have already mentioned above this all the things again working fine in emulator in android studio.
so is there any Progress dialog or async task unsupported things in Android TV.
I have seen with so many links on Google but doesn't find out any of the points.
Could u please help me out or Suggest to run my app in Android TV.
Thanks in advance.

**Comment by ryanseys** [comment]
Are you still seeing this issue? I have had no problem installing it recently using the Android Marshmallow emulator.

**Comment by testuser34** [comment]
Hi ryan,
The issue is not about to installed google sample that is done successfully as per your below comments.

https://github.com/googlesamples/androidtv-Leanback/blob/b09a46461b032265c61cdc66ba74714ea806f392/app/build.gradle#L7

https://github.com/googlesamples/androidtv-Leanback/blob/b09a46461b032265c61cdc66ba74714ea806f392/app/src/main/AndroidManifest.xml#L19

But now i am going to create customize TV app using same library.

So i have already developed few things like sign in and listing of some data in my App.

With using AsyncTask in app i am sending and receiving data.

While i am testing all the developed things in emulator it's working fine.

But my developed app which is working in emulator while i am installing it in android TV and if i run my app then when i enter login details and click on Login button it is going on HomeScreen of tv app everytime.

while same thing working successfully in Emulator.

So I am not getting what is the issue facing while Running on TV.

So is there any Progress dialog or AsyncTask unsupported things in Android TV .

Thanks in advance.

**Comment by ryanseys** [comment]
Are there any errors or messages that are being logged to logcat when this happens? The emulator should work for all aspects of the Android TV experience. Please provide a bit more information so that we can discuss this issue in greater detail. Thanks!

**Comment by testuser34** [comment]
Hi Ryanseys,

Thanks for your reply.

Not any Error or Logs are showing while running app in EMULATOR like AsyncTask and Progress Dialogs are Working Perfect in Emulator.

Now whatever things i have developed for my TV app is already working with EMULATOR.

Flow of My TV app Starting with Signin Functionality.

But while i am installing generated APK in Real Android TV Device and When Sign In page opens.

While i am Sending Sign In Request to Server and When click On Sign In Button it is Redirecting on TV Home screen every time.

While this thing is in Working mode in Emulator.

I have generated logs also through web service at server side.

The Sign In web service in Android TV call till DoInBakcground then it is Redirecting on Home Screen every time.

This is the issue i am facing.

Thanks in advance.

**Comment by Fleker** [comment]
Hey @testuser34 are you still seeing this problem?
