### ISSUE TITLE
Modify ImageCardView to show text instead of image

### ISSUE THREAD

**Issue by atentis** [googlesamples/androidtv-Leanback#61]
@ryanseys  Hello, I am working with the Leanback Library Sample and would like to make a change to how the cards look. When viewing the cards as a list as well as in the detailed focused view I would like to remove the image and add some text there instead.

What would be the best way to go about doing this while still preserving the look and feel of the leanback cardview? Here are some images to show what I am looking to do. Thanks!

![image](https://cloud.githubusercontent.com/assets/8903400/13244001/a1119a6a-d9c8-11e5-9c5d-5fb52b861a35.png)
 
![image](https://cloud.githubusercontent.com/assets/8903400/13244011/b1b94bba-d9c8-11e5-94bb-e7b6851a8340.png)

**Comment by ryanseys** [comment]
@atentis Great question. Easiest way IMO would be to render an image with that text you want. Leanback isn't designed to allow a lot of flexibility in this sense, it is a package of UI/UX best practices and given as a convenience to developers. We encourage developers to use Leanback as-is, however those that decide to deviate from this are the exception and in these cases we assume these developers can work out a custom solution themselves. 

All that said, I'll walk you through my approach, assuming I was in your shoes and needed these changes.

The first image you show is the result of the CardPresenter which uses a ImageCardView under the hood. The ImageCardView extends BaseCardView. Unfortunately there's does not exist a similar class like "TextCardView" that allows you to set text, so your approach should be to create this new class (e.g. call it TextCardView) and make it extend the BaseCardView and include any text elements you would like in that view. Then instead of using an ImageCardView in the CardPresenter, use your new TextCardView.

For the second one, it's a little more tricky but the same approach applies. This is the result of the DetailsDescriptionPresenter which renders a DetailsOverviewRow, which extends Row. Rather than creating a new class that extends Row, it might be easier to extend DetailsOverviewRow and overlay any text elements you need over this.

I hope this helps but I do encourage you to use the Leanback library as it is, as it represents the current best practices we encourage for developing great Android TV apps.

I've made note of your request internally, I think it might be valuable to have a TextCardView, as I described above to address cases like this.

Cheers and good luck!

**Comment by atentis** [comment]
@ryanseys Thanks Ryan. I have started creating my own TextCardView class. Hopefully I can come up with something. Appreciate your help!
