### ISSUE TITLE
VerticalGridFragment turn off dimming of cards

### ISSUE THREAD

**Issue by atentis** [googlesamples/androidtv-Leanback#78]
@Fleker or anyone else that contributes to the leanback sample...

I am working on VerticalGridFragment that does not do anything but display the cards. To do this I am making some slight changes. I do not want the user to be able to focus on the cards or open them. That was easy and I just set cardView.setFocusable(false); in the CardPresenter. _This is complete._ However, I could not find the following...
1.  I would like all of the cards to not have the dim look and am having trouble finding where this is set. I would all cards to look equally bright.
2. I have increased my CardView sizes in the CardPresenter and now the VerticalGridFragment shows the group of cards off center. Do you know where I can change the padding around the group of cards?

Any help on these two modifications would be great.

Thanks a ton!

Adam

**Comment by Fleker** [comment]
That's an interesting use case. I think the easiest solution would be to
override the on key events and prevent them from doing anything.

On Oct 16, 2016 12:53 PM, "Adam Tentis" <notifications@github.com> wrote:

@Fleker <https://github.com/Fleker> or anyone else that contributes to the
leanback sample...

I am working on VerticalGridFragment that does not do anything but display
the cards. I do not want the user to be able to focus on the cards or open
them. That was easy and I just set cardView.setFocusable(false); in the
CardPresenter. However, I would like all of the cards to not have the dim
look and am having trouble finding where this is set.

Can you point me in the right direction where I could modify this so all
the cards in the VerticalGridFragment look bright?

Thanks!

Adam

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/googlesamples/androidtv-Leanback/issues/78>, or mute
the thread

**Comment by Fleker** [comment]
If you override [`dispatchKeyEvent`](https://developer.android.com/reference/android/app/Activity.html#dispatchKeyEvent(android.view.KeyEvent)) and always return false, it will prevent the user from pressing buttons and prevent focus from changing.

**Comment by atentis** [comment]
@Fleker That will stop the cards from displaying a dimmed tone?

**Comment by Fleker** [comment]
If you do that instead of setting focusable to false, users will be unable to navigate the app and focus on cards.

**Comment by atentis** [comment]
@Fleker I see what you are saying but that is not what I am looking for. I just need to stop the dimming of the cards. I want them all to look equally bright. 

This is only one of many fragments in the app. Users will need to navigate the app but not this view and thats why cardView.setFocusable(false) works for part of this. I know i mentioned slideshow earlier but that is just for this fragment. Users will be able to leave it.

**Comment by Fleker** [comment]
I recall a similar sort of issue with the sample regarding the [`IconHeaderItemPresenter`](https://github.com/googlesamples/androidtv-Leanback/blob/b695fe0e8a6d47ce3748b354c0c2cdba89350bdf/app/src/main/java/com/example/android/tvleanback/presenter/IconHeaderItemPresenter.java)

Can you just manually set the alpha to `1.0` when you create your card?

**Comment by atentis** [comment]
Doesn't seem to have an effect on dimming. I tried it in the CardPresenter like below.

`@Override
    public ViewHolder onCreateViewHolder(ViewGroup parent) {
     ......
     ......
        ImageCardView cardView = new ImageCardView(parent.getContext()) {
            @Override
            public void setSelected(boolean selected) {
                updateCardBackgroundColor(this, selected);
                super.setSelected(selected);
            }
        };
        
        cardView.setAlpha(1.0f); //Remove dimming here.
        
        cardView.setFocusable(true);
        cardView.setFocusableInTouchMode(true);
        updateCardBackgroundColor(cardView, false);
      
        return new ViewHolder(cardView);
    }
`

**Comment by Fleker** [comment]
I'm not sure then. Maybe take another look at the IconHeaderItemPresenter to understand the lifecycle some more.

**Comment by atentis** [comment]
After spending some time I don't think setting the alpha is what is handling the dim look on the cards. I found out I can modify the cardView.setAlpha in the CardPresenter by turning **down** the alpha. 

The reason it didn't look like it did anything before was because the alpha was already maxed out and is not what is making the cards dim.  So somewhere else the dimming is being set and is probably not an alpha setting. 

So unfortunately I dont think the IconHeaderItemPresenter code is going to help me since that is using the alpha. Ugh, this is tough one.

**Comment by vcluan** [comment]
Dig deeper in VeticalGridPresenter, you will see mUseFocusDimmer.
Use this new VerticalGridPresenter(FocusHighlight.ZOOM_FACTOR_LARGE, false);

**Comment by atentis** [comment]
@vcluan  I ended up getting help from another developer that showed me the same thing. Thanks!

**Comment by theKeval** [comment]
@atentis @vcluan I've similar kind of issue. I want to reduce the dim level instead of removing dimmer completely. is that possible for VerticalGridPresenter?

I found that "lb_view_dimmed_level" can reduce dimming of whole leanback app but i want to reduce demming just for this specific VerticalGridPresenter.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
